In [ ]:
                                '''IPA 0.1'''

In [ ]:
'''Sample Test-case 1:
Input :

5
Sunita
Faculty
23000
2
jan
4
March
6
Arun
Admin
30000
3
Feb
4
March
12
June
10
Dipak
Admin
25000
3
Jan
12
July
5
Aug
3
Balen
HR
12000
3
Jan
12
July
5
Aug
3
Tarun
HR
78000
3
Jan
12
July
5
Aug
3
18
100


Output:

Sunita False
Arun True
Dipak True
Balen True
Tarun True
8600


Sample Test-case 2 :
Input :

5
Sunita
Faculty
23000
4
jan
4
March
6
apr
6
June
3
Arun
Admin
30000
3
jan
4
March
6
apr
6
Dipak
Admin
25000vc
3
jan
4
March
6
apr
6
Balen
HR
12000
3
jan
4
March
6
apr
6
Tarun
HR
78000
3
jan
4
March
6
apr
6
30
100


Output :

Sunita False
Arun False
Dipak False
Balen False
Tarun False
0'''

In [8]:


class Employee:
    def __init__(self,employee_name,designation,salary,overTimeContribuiton):
        self.employee_name = employee_name
        self.designation = designation
        self.salary = salary
        self.overTimeContribuiton = overTimeContribuiton
        self.overTimeStatus = False

'         
            
class Organization(Employee):
    def __init__(self,employee_list):
        self.employee_list = employee_list

      
    def isEligibleBonus(self,overTimeThreshold):
        for i in self.employee_list:
            totlOverTimeHours = sum(employee.overTimeContribuiton.values())
            if totlOverTimeHours >= overTimeThreshold:
                overTimeStatus = True


    def totalBonusToBePaid(self,rateperhour):
        total_bonus = 0
        for i in self.employee_list:
            if i.overTimeStatus:
                totlOverTimeHours = sum(employee.overTimeContribuiton.values())
                bonus = totlOverTimeHours*rateperhour
                total_bonus = total_bonus + bonus
        return total_bonus 
                    
 


#main code


l  =[]
for j in range(n):
    employee_name = input()
    designation = input()
    salary = int(input())

    overTimeContribuiton = {}
    number_of_overTimeContribuiton = int(input())
    for k in range(number_of_overTimeContribuiton):
        key = input()   
        value = int(input())
        overTimeContribuiton[key] = value
    
    employee = Employee(employee_name,designation,salary,overTimeContribuiton)
    l.append(employee)


org_obj = Organization(l)
overTimeThreshold = int(input())
rateperhour = int(input())


org_obj.isEligibleBonus(overTimeThreshold)
total_bonus = org_obj.totalBonusToBePaid(rateperhour)

for i in l:
    print(i.employee_name,i.overTimeStatus)
    
print(total_bonus)

1
ram
HR
30000
3
jan
4
feb
12
mar
10
18
100
ram False
0

In [ ]:
                                            '''IPA 0.2'''

In [ ]:
'''

3
3
1
Hamlet
shakesphere
2
Macbeth
SHAKESPHERE
3
othello
Shakesphere
A-10
gomtinagar
lucknow
u.p.
201876
3
1
A Christmas Carol.
Charles Dickens
2
Bleak House
Charles Dickens
3
Oliver Twist
Charles Dickens
A-770
rajamandi
agra
u.p.
2018763
3
1
The adventures of sherlock holmes
sherlock holmes
2
The return of sherlock holmes
sherlock holmes
3
The sign of the four
sherlock holmes
A-660
Khairatabad
lucknow
u.p.
201876
lucknow


Output :

SHAKESPHERE 3
['othello', 'Macbeth', 'Hamlet', 'The sign of the four', 'The return of sherlock holmes', 'The adventures of sherlock holmes']'''

In [ ]:

class Book:
    def __init__(self,b_i,b_n,n_a):
        self.b_i = b_i
        self.b_n = b_n
        self.n_a = n_a
        
        
class Library(Book):
    def __init__(self,lis_bt,dic_add_lib):
        self.lis_bt = lis_bt
        self.add_lib =  add_lib
        
    def count_books(self):
        di = {}
        l1=[]
        for i in self.lis_bt:
            l1.appeni.n_a.upper())
        authors = list(set(l1))
            
        for aut in authors:
            di[aut] = li.count(aut)
            
        return di
               
def lis_books_lib(city,l):
    lis_books = []
    for i in l:
        if i.d['city']==city:
            tempBooks = 0
            for book_obj in i.l1:
                    tempBooks.append(book_obj.b_n)
                tempBooks.reverse()
                lis_books = lis_books + tempBooks
    return lis_ books
              
        
        
#main programm       



n = int(input())               #count of library object
l=[]                           #list of library object

for i in range(n):
    l1 = []                   #list of book object
    d={}
    numBooks = int(input())   #count of book objects
    
    for j in range(numBooks):      
        b_i = int(input())
        b_n = input()
        n_a = input()
        l1.append(Book(b_i,b_n,n_a))
    
    d['street'] = input()
    d['area'] = input()
    d['city'] = input()
    d['state'] = input()
    d['zip'] = input()
    l.append(Library(l1,d))
    
    
city = input()
for k in l:
    
    obj = libObj[j]
    res = obj.booksByAuthors()
    print(*res.keys(), *res.values())
books = findbookType(city,libObj)
print(books)

In [ ]:
22
  
23
def books_present(city,l):
24
 l4=[]
25
 
26
 for i in l:
27
  if i.d['C'].lower()==city.lower():
28
    for m in i.l1[::-1]:
29
     l4.append(m.BN)
30
​
31
 return l4    
32
​
33
 
34
  
35
   
36
    
37
n=int(input())
38
l=[]
39
for i in range(n):
40
 l1=[]
41
 d={}
42
 n1=int(input())
43
 for j in range(n1):
44
  ID=int(input())
45
  BN=input()
46
  AN=input().upper()
47
  l1.append(Book(ID,BN,AN))
48
 d["S"]=input()
49
 d["A"]=input()
50
 d["C"]=input()
51
 d["State"]=input()
52
 d["Z"]=input()
53
 l.append(Library(l1,d))
54
city=input()
55
  
56
o1=Library(l[0].l1,l[0].d)
57
o2=o1.Aut_count()
58
for k,v in o2.items():
59
 print(k,v)
60
o3=books_present(city,l)
61
print(o3)

In [ ]:
o1=Library(l[0].l1,l[0].d)

In [ ]:
                                    '''IPA 0.3'''

In [ ]:
'''Sample Input:
2
12345
12
30.0
10.0
salary
45678
98
400.0
200.0
salary
45678
98
100.0
salary

Output:
45678 300.0 100.0
12345 30.0
45678 300.0'''

In [67]:
class Account:
    def __init__(self, CN, P, B, W, AT):
        self.CN = CN
        self.P = P
        self.B = B
        self.W = W
        self.AT = AT

    def update_balance(self, W1):
        if W1 <= self.B:
            self.B = self.B - W1
            self.W = W1


class ATM(Account):
    def __init__(self, l):
        self.l = l

    def ATM_Bal(self, CN1, P1, W2):
        for obj in self.l:
            if obj.CN == CN1 and obj.P == P1:
                obj.update_balance(W2)
                return obj
        return None

    def Filter_Ac(self, AT2):
        d = {}
        for obj in self.l:
            if obj.AT.lower() == AT2.lower():
                d[obj.CN] = obj.B
        dd = dict(sorted(d.items(), key=lambda x: x[1]))
        if dd == {}:
            return None
        else:
            return dd


l = []
n = int(input())
for _ in range(n):
    CN = int(input())
    P = int(input())
    B = float(input())
    W = float(input())
    AT = input()
    l.append(Account(CN, P, B, W, AT))

CN1 = int(input())
P1 = int(input())
W1 = float(input())
AT2 = input()

ATM_obj = ATM(l)
obj1 = ATM_obj.ATM_Bal(CN1, P1, W1)
if obj1 is not None:
    print(obj1.CN, obj1.B, obj1.W)
else:
    print("No account exists")

filter_acc = ATM_obj.Filter_Ac(AT2)
if filter_acc:
    for k, v in sorted(filter_acc.items()):
        print(k, v)
else:
    print("No match found")

2
12345
12
30.0
10.0
salary
45678
98
400.0
200.0
salary
45678
98
100.0
salary
45678 300.0 100.0
12345 30.0
45678 300.0

In [ ]:
                                        '''IPA1'''

In [ ]:
'''Sample Input :
2          =>.The first input taken in the main section is the number of Tournament Objects to be created n.



3    => next set of inputs are related to n Tournament objects to be created as follows:

12
UEFA
Portugal
106
AFC
India
86
AFC
China

TriNationSeries2020
India
7
2020
3
3                      =>time



4

1              =>ranking
SA             =>zone
Argentina      =>teamname
5
UEFA
England
12
UEFA
Portugal
3
UEFA
Netherlands


ChampionsCup2021    =>Name
England             =>host
7                   =>edition
2021                =>year
4                   =>participants
2                   =>time


3         => Time, supplied as a argument to the second function

Sample Output :
UEFA - 1
AFC - 2
Portugal
China
India
'''

In [24]:
class Team:
    def __init__(self,tR,tC,tN):
        self.tR = tR
        self.tC = tC
        self.tN = tN

class Tournament(Team):
    def __init__(self,l,di):
        self.l=l
        self.di=di


    def Conf(self):             #and returns a dictionary having the confederation and teamCount (count of Teams) as key : value pairs
        d={}
        l1=[]
        for i in self.l:
            l1.append(i.tC)
        l2=list(set(l1))
        for j in l2:
            d[j]=l1.count(j)
            
        return d 
    
def meth_2(num,li):
    li_teams=[]
    
    for i in li:
        if num==i.di["time"]:
            li_teams.append(i)
            
    dic={}
    for i in li_teams:
        for j in i.l:
            dic[j.tR]=j.tN
    
    li_team_2=[]
    dd = dict(sorted(dic.items()))
    for i in dd.keys():
        li_team_2.append(dd[i])
    
    if li_team_2==[]:
        return None
    else:
        return li_team_2

#main code
li=[]
n=int(input())
for i in range(n):
    l=[]
    n1 = int(input())
    for j in range(n1):
        tR = int(input())
        tC = input()
        tN = input()
        l.append(Team(tR,tC,tN))

    di={}
    di["name"]=input()
    di["host"]=input()
    di["edition"]=int(input())
    di["year"]=int(input())
    di["participants"]=int(input())
    di["time"]=int(input())
    li.append(Tournament(l,di))
    
num = int(input())

tn = li[0].Conf()             #he line tn = li[0].Conf() means that you are accessing the first object (li[0]) in the li list and calling its Conf() method.
for i in tn.keys():
    print(i,"-",tn[i])

ans = meth_2(num,li)
if ans==None:
    print("No Team Found")
else:
    for i in ans:
        print(i)

2
3
12
UEFA
POR
106
AFC
IND
86
AFC
CHI
TRINATION
IND
7
2020
3
3
4
1
SA
ARG
5
UEFA
ENG
12
UEFA
POR
3
UEFA
NED
CHAMPIONS
ENG
7
2021
4
2
3
UEFA - 1
AFC - 2
POR
CHI
IND

In [15]:
dic  = { 'D': 1, 'B': 4, 'C': 3 }

dd = dict(sorted(dic.items()))
print("dd is",dd)

l=[]
dic1  = { 3:"C",4:"B",1:"D"}
dd2 = dict(sorted(dic1.items()))
dd3=dict(sorted(dic.items(), key=lambda x:x[1]))  #dict nhi use kel tr list return hote
dd4=sorted(dic.items(), key=lambda x:x[1],reverse=True)
print("dd2 is",dd2)
print("dd3 is",dd3)
print("dd4 is",dd4)
for i in dd2:
    l.append(dd2[i])
print("l is",l)

dd is {'B': 4, 'C': 3, 'D': 1}
dd2 is {1: 'D', 3: 'C', 4: 'B'}
dd3 is {'D': 1, 'C': 3, 'B': 4}
dd4 is [('B', 4), ('C', 3), ('D', 1)]
l is ['D', 'C', 'B']

In [ ]:
def meth_2(num, li):
    li_teams = []  # Initialize an empty list to store the tournaments that match the given time

    # Iterate over each tournament in the list
    for i in li:
        if num == i.di["time"]:  # Check if the tournament's time matches the given time
            li_teams.append(i)  # If it matches, add the tournament to the list

    dic = {}  # Initialize an empty dictionary to store team rankings
    for i in li_teams:  # Iterate over the tournaments that match the given time
        for j in i.l:  # Iterate over the teams within each tournament
            dic[j.tR] = j.tN  # Store the team ranking (tR) as the key and team name (tN) as the value in the dictionary

    li_team_2 = []  # Initialize an empty list to store the sorted team names
    dd = dict(sorted(dic.items()))  # Sort the dictionary items based on the team rankings and create a new sorted dictionary
    for i in dd.keys():  # Iterate over the sorted dictionary keys
        li_team_2.append(dd[i])  # Append the team name to the sorted list based on the sorted dictionary keys

    if li_team_2 == []:  # Check if the sorted list is empty
        return None  # If it is empty, return None
    else:
        return li_team_2  # If it is not empty, return the sorted list of team names

In [ ]:
                                        '''IPA 2 '''

In [ ]:
'''Sample Input:
8
Coda
2021
3
3
Italy
Drive my car
2021
1
4
Japan
Tenet
2020
1
2
America
6
Soul
2020 23
America
Mank
2020 2
10
America
Marriage Story
2019 16
America
Birdman
2014 49
America
Belfast
2021 17
Britain
2021
Sample Output:
Coda
2021 33
Italy
Drive my car
2021 14
Japan
Belfast
2021 17
Britain


Coda 100
Soul 66
Tenet 50
Birdman 44
Drive my car 25
Mank 20
Marriage Story 16
Belfast 14'''

In [33]:
class MovieInfo:
    def __init__(self,T,Y,A,N,C):
        self.T=T
        self.Y=Y
        self.A=A
        self.N=N
        self.C=C

In [34]:
class Award(MovieInfo):
    def __init__(self,l):
        self.l=l
        
    def non_american(self,year):
        li=[]
        for i in self.l:
            if i.Y == year and i.C!="America":
                li.append(i)
                
        if li==[]:
            return None
        else:
            return li
                
    def success_rate(self):
        d={}
        for i in self.l:
            sucessRate=int((i.A/i.N)*100)
            d[i.T] = sucessRate
            
        di=dict(sorted(d.items(), key=lambda x:x[1],reverse=True))
        return di

In [35]:
#main code
l=[]
n = int(input())  #no.of object of Movieinfo
for i in range(n):
    T = input()
    Y =int(input())
    A =int(input())
    N =int(input())
    C =input()
    l.append(MovieInfo(T,Y,A,N,C))

year=int(input())

output=Award(l)
output1=output.non_american(year)
if output1==None:
    print("No movie found")
else:
    for i in output1:
        print(i.T)
        print(i.Y)
        print(i.A)
        print(i.N)
        print(i.C)

output2=output.success_rate()

if output2:
    for k,v in output2.items():
        print(k,v)
else:
    print("Unable to create dictionary")

8
coda
2021
3
3
Italy
Drive My Car
2021
1
4
Japan
Tenet
2020
1
2
America
Soul
2020
2
3
America
Mank
2020
2
10
America
Marriage Story
2019
1
6
America
Birdman
2014
4
9
America
Belfast
2021
1
7
Britain
2021
coda
2021
3
3
Italy
Drive My Car
2021
1
4
Japan
Belfast
2021
1
7
Britain
coda 100
Soul 66
Tenet 50
Birdman 44
Drive My Car 25
Mank 20
Marriage Story 16
Belfast 14

In [ ]:
#output obitained is
'''coda
2021
3
3
Italy
Drive My Car
2021
1
4
Japan
Belfast
2021
1
7
Britain
coda 100
Soul 66
Tenet 50
Birdman 44
Drive My Car 25
Mank 20
Marriage Story 16
Belfast 14'''

In [ ]:
                                                    '''IPA3'''

In [ ]:
'''Sample Input1:
5
101
Tanmay
delhi
90
88
93
102
Sunil
delhi
90
95
90
103
Karvi
maharashtra
70
45
50
104
monika
tamilnadu
20
35
40
105
Ram
tamilnadu
90
65
50
a
Sample Output1:
102 sunil 275 A delhi
101 tanmay 271 A delhi
delhi 100:0
maharashtra 100:0
tamilnadu 50:50
'''

In [36]:
class Scholar:
    def __init__(self,I,N,S,M):
        self.I = I
        self.N = N
        self.S = S
        self.M = M

In [60]:
class Scholar:
    def __init__(self,I,N,S,M):
        self.I = I
        self.N = N
        self.S = S
        self.M = M

class ScholarResult(Scholar):
    def __init__(self):
        self.li = li
        
    def grade(self,l,grade):
      
        d={}
        grade1=""
        for i in self.l:
            per = round(sum(i.M)/3)
            if per>=80:
                grade1="A"
            elif per>=60 and per<80:
                grade1="B"
            elif per>=50 and per<60:
                grade1="C"
            else:
                grade1="D"
            
            d["I"]=i.I
            d["N"]=i.N
            d["TotalMarks"]=per
            d["Grade"]=grade1
            d["S"]=i.S
            self.li.append(d)
        
        li2=[]
        for j in self.li:
            if j['Grade']==grade:
                li2.append(j)
        
        li3=sorted(li2, key=lambda x:(x['TotalMarks']), reverse="True")
        
        if self.li==[]:
            return None
        else:
            return li3
    
    
    def pass_fail(self):
        li4=[]
        di2={}
        count=0
        for i in self.li:
            if i["Grade"]!="D":
                count=count+1
        
        for j in self.li:
            pp=round((count/j[N])*100)
            ff=round(((j[N]-count)/j[n])*100)
            
            li4.append(j.,pp:ff)
        
        if li4==[]:
            return None
        else:
            return li4
            
            
n=int(input())
l=[]
for i in range(n):
    I = int(input())
    N = input()
    S = input()
    M1 = int(input())
    M2 = int(input())
    M3 = int(input())
    M = [M1,M2,M3]
    l.append(Scholar(I,N,S,M))
    
grade = input().upper()

SyntaxError: invalid syntax (Temp/ipykernel_15060/1903145876.py, line 51)

In [ ]:
#main code
n=int(input())
l=[]
for i in range(n):
    I = int(input())
    N = input()
    S = input()
    M1 = int(input())
    M2 = int(input())
    M3 = int(input())
    M = [M1,M2,M3]
    l.append(Scholar(I,N,S,M))
    
grade = input().upper()

In [39]:
grade = input().upper()
print(grade)

a
A

In [50]:
M = [1,2.9,3.7] 
per = round(sum(M)/3)
per

3

In [45]:
1+2.9+3.7

7.6

In [47]:
7.6/3

2.533333333333333

In [49]:
round(2.4)

2

In [55]:
grade=""
l=[12,8]
li=["A","B"]
for i in l:
    if i>10:
        grade="A"
        
print(grade)

A

In [ ]:
class Scholar:
def __init__(self, scholar_id, scholar_name, state, marks):
self.scholar_id = scholar_id
self.scholar_name = scholar_name
self.state = state
self.marks = marks
class ScholarGrade:
def __init__(self):
self.scholar_grade = []
def calculate_grade_return(self, scholar_list, grade):
grade_list = ['A', 'B', 'C', 'D']
key_list = ['scholar_id', 'scholar_name', 'total_marks', 'grade', 'state']
if len(scholar_list) > 0:
for i in scholar_list:
assign_grade = ''
total_marks = sum(i.marks)
percentage = int(round(total_marks / 3, 0))
if percentage >= 80:
assign_grade = grade_list[0]
elif 60 <= percentage < 80:
assign_grade = grade_list[1]
Restricted for circulation outside TCS Xplore 8
Not to be circulated
elif 50 <= percentage < 60:
assign_grade = grade_list[2]
else:
assign_grade = grade_list[3]
student_record_list = [i.scholar_id, i.scholar_name,
total_marks, assign_grade, i.state]
student_record = dict(zip(key_list, student_record_list))
self.scholar_grade.append(student_record)
find_scholar = [rec for rec in self.scholar_grade if rec['grade'] == grade]
find_scholar = sorted(find_scholar, key=lambda x: (x['total_marks']), reverse=True)
return find_scholar
else:
return None
def display_statewise_result(self):
if len(self.scholar_grade) == 0:
return None
else:
state_pass_fail_ratio = []
states = list(set([each_record['state'] for each_record in self.scholar_grade]))
states.sort()
for item in states:
count_scholars = 0
count_fail = 0
for each_record in self.scholar_grade:
if each_record['state'] == item:
count_scholars += 1
if each_record['grade'] == 'D':
count_fail += 1
fail_percentage = int(round((count_fail / count_scholars) * 100, 0))
count_pass = count_scholars - count_fail
pass_percentage = int(round((count_pass / count_scholars) * 100, 0))
one_state_record = [item, f'{pass_percentage}:{fail_percentage}']
state_pass_fail_ratio.append(one_state_record)
return state_pass_fail_ratio
scholar_count = int(input())
scholar_list = []
for i in range(scholar_count):
scholar_id = int(input())
scholar_name = input().lower()
state = input().lower()
Restricted for circulation outside TCS Xplore 9
Not to be circulated
sub1_marks = int(input())
sub2_marks = int(input())
sub3_marks = int(input())
marks = [sub1_marks, sub2_marks, sub3_marks]
scholar_obj = Scholar(scholar_id, scholar_name, state, marks)
scholar_list.append(scholar_obj)
grade = input().upper()
scholar_grade_obj = ScholarGrade()
student_list_with_grade = scholar_grade_obj.calculate_grade_return(scholar_list, grade)
if student_list_with_grade is None or len(student_list_with_grade) == 0:
print("No Record Found")
else:
for record in student_list_with_grade:
for k, v in record.items():
print(v, end=" ")
print()
pass_fail_ratio_statewise = scholar_grade_obj.display_statewise_result()
if pass_fail_ratio_statewise is None:
print("No Record Found")
else:
for record in pass_fail_ratio_statewise:
for item in record:
print(item, end=" ")
print()

In [ ]:
                                                '''IPA4'''

In [64]:
class Runner:
    def __init__(self,NR,NC,Dis,T):
        self.NR=NR
        self.NC=NC
        self.Dis=Dis
        self.T=T

In [65]:
class RunningRace(Runner):
    def __init__(self,l):
        self.l=l
        
    def runner_pace(self,pace):
        l1=[]
        for i in self.l:
            pace1=i.T/i.Dis
            if pace1<pace:
                l1.append(i.NR)
        
        if l1==[]:
            return None
        else:
            return l1

In [66]:
n =int(input())
l=[]
for i in range(n):
    NR=input()
    NC=input()
    Dis=float(input())       #in km
    T=int(input())           #in min
    l.append(Runner(NR,NC,Dis,T))
    
pace=int(input())        #in min/km

#jyancha pace less than ahe input peksha tyanche naw print kara if method return none then print("No runners found")
output=RunningRace(l).runner_pace(pace)
if output==None:
    print("No runners found")
else:    
    for i in output:
        print(i)

4
John
Fit4Life
5
20
Bob
TopRun
5
14
Rahul
FitDaily
10
38
Ria
StoicRunners
7
55
5
John
Bob
Rahul

In [68]:
l1=[4,4]
l2=list(set(l1))
l2

[4]

In [ ]:
                    '''GIT 1 -04'''

In [26]:
class Employee:
    def __init__(self, ID, N, R, AR):
        self.ID = ID
        self.N = N
        self.R = R
        self.AR = AR
        self.status = None

class Organization:
    def __init__(self, l, d):
        self.l = l
        self.d = d
    
    def eligibility_status(self):
        d1 = {}
        for i in self.l:
            for k,v in self.d.items():
                if i.R.lower() == k.lower():
                    if i.AR == v:
                        d1[i.ID] = "eligible"
                        i.status = True
                    elif i.AR > v:
                        d1[i.ID] = "overdue"
                        i.status = True
                    elif i.AR < v:
                        d1[i.ID] = str(v - i.AR) + " years left"
                        i.status = False
        return d1

l = []
n = int(input())
for _ in range(n):
    ID = input()
    N = input()
    R = input()
    AR = int(input())
    l.append(Employee(ID, N, R, AR))

d = {}
for _ in range(1):
    Role = input()
    Age = int(input())
    d[Role] = Age

o1 = Organization(l, d)
o2 = o1.eligibility_status()
for k, v in o2.items():
    print(k, v)

1
100
pra
er
4
er
5
100 1 years left

In [ ]:
                            '''GIT 2 -07'''

In [ ]:
class Employee:
    def __init__(self,N,D,S,LD):
        self.N=N
        self.D=D
        self.S=S
        self.LD=LD
        
class Organization(Employee):
    def __init__(self,l,l1,d1):
        self.l=l    #A list of Employee objects
        self.l1=l1  # A list of types of loans Organization offers to employees
        self.d1=d1  # Designation wise eligible maximum loan amount stored as key : value pairs - designation : maximum eligible loan amount.
    
    def Emp_eligible(self,name,loantype,borrowamt):
        for i in self.l:
            if i.N==name and loantype not in i.LD and loantype in self.l1:
                a=borrowamt
                for k,v in i.LD.items(): 
                    a = a+v
                for k1,v1 in self.d1.items():
                    if i.D==k1:
                        if a<v1:
                            i.LD[loantype]=borrowamt
                            return i
                        else:
                            return False
                        
    def des_count(self):
        d2={}
        for i in self.l:
            des=i.D
            a=0
            for k,v in i.LD.items():
                a=a+v
            if des in self.d1:
                if a<self.d1[des]:
                    if des not in d2:
                        d2[des]=1
                    else:
                        d2[des]=d2[des]+1
                            
                            
        
        
        
        
        
        
        
#main programm
l=[]
n=int(input())

for i in range(n):
    N = input()
    D = input()
    S = int(input())
    n1=int(input())
    
    LD={}
    for j in range(n1):
        LT = input()
        A = int(input())
        LD[LT] = A
    l.append(Employee(N,D,S,LD))
        
l1=[]
n2=int(input())
for i in range(n2):
    Loan_type=input()
    l1.append(Loan_type)
    
d1={}
n3=int(input())
for i in range(n3):
    DES=input()
    Eli_A=int(input())
    d1[DES]=Eli_A
    
name=input()
loantype=input()
borrowamt=int(input())

In [ ]:
# 5
# Sunita
# Faculty
# 23000
# 1
# Home
# 200000
# Arun
# Programmer
# 30000
# 1
# Personal
# 4000
# Dipak
# Tester
# 25000
# 2
# Travel
# 10000
# Personal
# 5000
# Balen
# Analyst
# 12000
# 1
# Travel
# 2000
# Tarun
# Programmer
# 78000
# 2
# Personal
# 100000
# Travel
# 2000
# 3
# Travel
# Home
# Personal
# 3
# Programmer
# 300000
# Faculty
# 200000
# Analyst
# 100000
# Tarun
# Home
# 50000

class Employee:
    def __init__(self,empName,empDesignation, empSalary, loan):
        self.empName = empName
        self.empDesignation = empDesignation
        self.empSalary = empSalary
        self.loan = loan

class Organization:
    def __init__(self,empObj,loanType,maxDesiganationAmount):
        self.empList = empObj
        self.loanType = loanType
        self.maxDesiganationAmount = maxDesiganationAmount

    def eligibleForLoan(self,name,type,amount):
        isFound = False
        for obj in self.empList:
            if obj.empName.lower() == name.lower() and type.lower() not in obj.loan and type.lower() in self.loanType:
                su = amount

                for _,v in obj.loan.items():
                    su = su + v

                for k,v in self.maxDesiganationAmount.items():
                    if k == obj.empDesignation.lower():
                        if su < v:
                            obj.loan[type] = amount
                            return obj
                        else:
                            return False
        if not isFound:
            return False

    def stillEligibleForLoan(self):
        eligible = {}
        for obj in self.empList:
            su = 0
            des = obj.empDesignation
            for k,v in obj.loan.items():
                su = su + v
            if des.lower() in self.maxDesiganationAmount:
                if su < self.maxDesiganationAmount[des.lower()]:
                    if des not in eligible:
                        eligible[des] = 1
                    else:
                        eligible[des] = eligible[des] + 1
                else:
                    eligible[des] = 0
        dic1 = dict(sorted(eligible.items(), key=lambda item:item[0], reverse=True))
        return dic1

empObj = []
for _ in range(int(input())):
    empName = input()
    empDesignation = input()
    empSalary = int(input())
    loan = {}
    for i in range(int(input())):
        key = input().lower()
        value = int(input())
        loan[key] = value
    empObj.append(Employee(empName,empDesignation,empSalary,loan))

loanType = []
for _ in range(int(input())):
    inp = input().lower()
    loanType.append(inp)

maxDesiganationAmount = {}
for _ in range(int(input())):
    key = input().lower()
    value = int(input())
    maxDesiganationAmount[key] = value

name = input()
type = input()
amount = int(input())

obj = Organization(empObj,loanType,maxDesiganationAmount)
res = obj.eligibleForLoan(name,type,amount)
if res:
    print("Loan Granted.")
    for k,v in res.loan.items():
        print(k,": ",v)
else:
    print("Not Found")

eligible = obj.stillEligibleForLoan()
for k,v in eligible.items():
    print(k,": ",v)

In [ ]:
                '''GIT BankBalance'''

In [35]:
class Account:
    def __init__(self,AN,N,B):
        self.AN=AN
        self.N=N
        self.B=B
    
    def deposite_money(self,dep_amt):
        self.B=self.B+ dep_amt
        return self.B
        
    
    def withdraw_money(self,with_amt):
      
        if self.B-with_amt>1000:
            self.B=self.B-with_amt
            return self.B
        else:
            return None
            
AN=int(input())
N=input()
B=int(input())
dep_amt=int(input())
with_amt=int(input())

o1=Account(AN,N,B)
o2=o1.deposite_money(dep_amt)
o3=o1.withdraw_money(with_amt)
print(o2)
if o3==None:
    print("insufficient Balance")
else:
    print(o3)

12345
pranay
2000
700
500
2700
2200

In [32]:
class Account:
    def __init__(self, AN, N, B):
        self.AN = AN
        self.N = N
        self.B = B
    
    def deposit_money(self, dep_amt):
        self.B = self.B + dep_amt
        return self.B
    
    def withdraw_money(self, with_amt):
        if self.B - with_amt > 1000:
            self.B = self.B - with_amt
            return self.B
        else:
            return None

AN = int(input())
N = input()
B = int(input())
dep_amt = int(input())
with_amt = int(input())

o1 = Account(AN, N, B)
o2 = o1.deposit_money(dep_amt)
o3 = o1.withdraw_money(with_amt)

print(o2)
if o3 is None:
    print("Insufficient Balance")
else:
    print(o3)

12345
Raj
1200
1500
2000
2700
Insufficient Balance

In [ ]:
                    '''git student grade'''

In [40]:
class Student:
    def __init__(self,R,N,l):
        self.R=R
        self.N=N
        self.l=l
        
    def cal_per(self):
        per = sum(self.l)/len(self.l)
        return per
    
    def find_grade(self,per):
        if per>=80:
            return "A"
        elif 80>per>=60:
            return "B"
        elif 60>per>=40:
            return "C"
        else:
            return "F"
        
R=int(input())
N=input()
n1=int(input())
l=[]
for i in range(n1):
    m=int(input())
    l.append(m)
    
o1=Student(R,N,l)
o2=o1.cal_per()
print(o2)
o3=o1.find_grade(o2)
print(o3)

200
Asha
4
90
90
80
60
80.0
A

In [ ]:
                            '''git cricket'''

In [49]:
class CricketPlayer:
    def __init__(self,N,l1,A,HC):
        self.N=N
        self.l1=l1
        self.A=A
        self.HC=HC

class Solution:
    def __init__(self,l):
        self.l=l
        
    def CountPlayers(self,Country):
        count=0
        for i in self.l:
            if i.HC==Country:
                count=count+1
        return count
    
    def final(self):
        c1=0
        d=""
        for i in self.l:
            a=len(i.l1)
            b=i.N
            if a>c1:
                c1=a
                d=b
                
        return d

In [50]:
#maincode
n=int(input())
l=[]
for i in range(n):
    N=input()
    
    n1=int(input())
    l1=[]
    for j in range(n1):
        C=input()
        l1.append(C)
    A=int(input())
    HC=input()
    l.append(CricketPlayer(N,l1,A,HC))
    
Country=input()
o1=Solution(l)
o2=o1.CountPlayers(Country)
print(o2)
o3=o1.final()
print(o3)

1
v
2
a
w
18
i
i
1
v